### ISSUE TITLE
Update column classes to use minus instead of plus

### ISSUE THREAD

**Issue by petealbertson** [HelpfulHuman/HelpfulUI#21]
The `+` sign as part of a class name is not supported by Jade, our preferred template language. This requires us to have to write `div(class='col +sm12')` instead of the preferred `div.col.+sm12` format. In addition to requiring more keystrokes than necessary, it means a single template will require multiple ways to declare a class. No bueno.

This might be trivial but while we're here, I think we should also adopt the more Bootstrappy convention of connecting the column modifier classes without spaces (i.e. `col-sm12`). This is more readable, particularly in Jade, and doesn't require escaping.

`div.col-sm12.col-md6.col-lg4` > `div.col.-sm12.-md6.-lg4`

**Comment by NickGlenn** [comment]
@petealbertson I think that this is an issue that could easily be resolved by using the proposed selector helpers found in issue #20.  We could allow developers the opportunity to define formatting using a variable like so:

``` stylus
$global__modifier-prefix = '.\+'
```

To use the prefix you selected, this could be changed to:

``` stylus
$global__modifier-prefix = '.\-'
```

Or to support a Bootstrap styled approach:

``` stylus
$global__modifier-prefix = '.&-'
```

**However**, there are 2 reasons I don't like Bootstraps' approach:
1. It's harder to differentiate between a modifier or a component that just has a hyphen: `.foo-bar`
2. You wind up with a long repetitive chain of classes: `.foo.foo-bar.foo-baz`

A better solution may just be a different prefix to `+`.  Something like `o-` could denote an option without adding a lot of extra characters.

Thoughts?

**Comment by petealbertson** [comment]
Perhaps my approach towards front-end tools is unsophisticated, but I think there is such a thing as too much abstraction. You've already heard me complain about this but I'm not a fan of writing front-end code in a way that's completely different from what the browser receives. I do a lot of tweaking and adjusting in the Chrome inspector and if I have to translate what I do there into entirely different functions or helpers, my work is slower. There's no _good_ reason why we can't define and use the proper class name formatting once in both our markup and stylesheets. I don't care if the modifier prefix is 💩 so long as it's readable, universally supported without escaping, and it persists in the client.

> 1. It's harder to differentiate between a modifier or a component that just has a hyphen: .foo-bar

This is a good point. Perhaps we can ban the use of hyphens except in modifier situations? I feel like there has to be another way to differentiate this and by itself is not a reason for abstracting class name formatting into a helper.

> 1. You wind up with a long repetitive chain of classes: .foo.foo-bar.foo-baz

Not trying to pick on you, @NickGlenn but we already have this kind of chain in our markup and I think you can argue it both ways. 
![image](https://cloud.githubusercontent.com/assets/5597250/9921902/7c1b9c5a-5c97-11e5-9294-a077236db7b7.png)

Furthermore, `.-md4` is a somewhat vague modifier by itself. Prepending with `.col` adds context which helps me understand what the modifier modifies, especially if I'm using multiple modifiers on the same element. Although I admit it's unlikely anyone is going to add other kinds of modifiers to a `div.col`.

**Comment by NickGlenn** [comment]
At the very least, I think an abstraction layer on the selectors makes sense for the modules maintained within Helpful UI's own stylus library.  That way you can change the classes to we provide to whatever you prefer, simply by modifying a couple of setting variables.  After all, these classes are abstracted away in the library and are unaccessible otherwise.

In regards to your response to my first point, rather than restrict use of a single hyphen character you could always use double hyphen `--` to denote a modifier.  This is very similar to the approach that [BEM](https://css-tricks.com/bem-101/) takes.

**Comment by NickGlenn** [comment]
Decided to stick with the `+` sign for this release.  May change spec down the road in the next major number iteration.
