### ISSUE TITLE
Should we rename $globals to $settings?

### ISSUE THREAD

**Issue by NickGlenn** [HelpfulHuman/HelpfulUI#23]
Hey @petealbertson @JesseG316 @brunnerjosh @cgoodling, I would love your thoughts on this...

Purely a preference thing to try and help avoid confusion.  All `$globals` are are settings available to any module or plugin.

**Comment by brunnerjosh** [comment]
@NickGlenn I would agree that calling a variable `$setting` would be a better idea. If I didn't already know what a `$global` variable was, I could see that being confusing.

**Comment by cgoodling** [comment]
$setting is clear, could be a good convention, or $global-setting vs $setting ?

**Comment by NickGlenn** [comment]
Decided, renaming `$global` to `$settings`
